export const LIMITS = {
  UPLOAD_MIN_BYTES: 1024,
  UPLOAD_SESSION_TTL_H: 24,
  PART_URL_TTL_H: 6,
  PART_SIZE_DEFAULT: 32 * 1024 ** 2,
  PART_SIZE_MIN: 5 * 1024 ** 2,
  PART_COUNT_MAX: 10_000,

  VIDEO_MIN_LONG_EDGE: 640,
  VIDEO_MIN_SHORT_EDGE: 360,
  TRANSCODE_MAX_ATTEMPTS: 3,
  TRANSCODE_TIMEOUT_MULT: 4,
  TRANSCODE_TIMEOUT_MIN_S: 600,

  SERIES_PER_USER: 200,
  EPISODES_PER_SERIES: 500,
  TAGS_PER_EPISODE: 10,

  COMMENT_MAX_LEN: 1000,
  COMMENT_MAX_DEPTH: 1,
  COMMENT_EDIT_WINDOW_MIN: 15,
  BIO_MAX_LEN: 500,
  SYNOPSIS_MAX_LEN: 2000,

  FEED_PAGE_DEFAULT: 20,
  FEED_PAGE_MAX: 50,

  PROGRESS_MIN_INTERVAL_S: 15,
  VIEW_COUNT_MIN_WATCH_S: 30,

  REPORT_DAILY_COUNT: 20,
  COMMENT_PER_10MIN: 30,

  SOFT_DELETE_PURGE_DAYS: 90,
  ORPHAN_ASSET_PURGE_DAYS: 7,
  FAILED_ASSET_PURGE_DAYS: 30,
} as const
