import type {
  Category,
  Chapter,
  Credit,
  EpisodeMetaView,
  EpisodeTranslation,
  SubtitleTrack,
} from '@aidream/core'
import { db } from '../client.js'
import { executeDb } from '../errors.js'

/** sitemap 한 항목. `lastModified` 는 Next `MetadataRoute.Sitemap` 이 요구하는 값이다. */
export interface SitemapEntry {
  readonly path: string
  readonly lastModified: Date
}

/**
 * `watch/[episodeId]` 의 `generateMetadata` 와 JSON-LD 가 쓰는 단일 조회.
 *
 * 페이지가 챕터·자막·크레딧·번역 테이블을 각각 알지 않게 한 번에 모은다.
 * 메타데이터는 비공개 작품에도 필요하다(작성자 본인 미리보기). 공개 여부
 * 판단은 호출자가 `visibility` · `status` 로 하고, 이 함수는 조회만 한다.
 */
export function findEpisodeMetaView(
  episodeId: string,
): Promise<EpisodeMetaView | null> {
  return executeDb(async () => {
    const row = await db.episode.findFirst({
      where: { id: episodeId, deletedAt: null },
      include: {
        series: {
          select: {
            id: true,
            slug: true,
            title: true,
            owner: {
              select: {
                handle: true,
                displayName: true,
                avatarKey: true,
                tier: true,
                verifiedAt: true,
              },
            },
          },
        },
        asset: { select: { durationSec: true } },
        category: true,
        chapters: { orderBy: { startSec: 'asc' } },
        credits: { orderBy: { order: 'asc' } },
        subtitles: { orderBy: { language: 'asc' } },
        translations: true,
      },
    })
    if (row === null) return null

    const chapters: readonly Chapter[] = row.chapters.map((chapter) => ({
      id: chapter.id,
      episodeId: chapter.episodeId,
      startSec: chapter.startSec,
      title: chapter.title,
    }))
    const credits: readonly Credit[] = row.credits.map((credit) => ({
      id: credit.id,
      seriesId: credit.seriesId,
      episodeId: credit.episodeId,
      userId: credit.userId,
      role: credit.role,
      name: credit.name,
      note: credit.note,
      order: credit.order,
    }))
    const subtitles: readonly SubtitleTrack[] = row.subtitles.map((track) => ({
      id: track.id,
      episodeId: track.episodeId,
      language: track.language,
      label: track.label,
      kind: track.kind,
      objectKey: track.objectKey,
      isDefault: track.isDefault,
      isAutoGenerated: track.isAutoGenerated,
    }))
    const translations: readonly EpisodeTranslation[] = row.translations.map(
      (translation) => ({
        episodeId: translation.episodeId,
        locale: translation.locale,
        title: translation.title,
        description: translation.description,
        metaTitle: translation.metaTitle,
        metaDescription: translation.metaDescription,
      }),
    )
    const category: Category | null =
      row.category === null
        ? null
        : {
            id: row.category.id,
            slug: row.category.slug,
            nameKo: row.category.nameKo,
            nameEn: row.category.nameEn,
            order: row.category.order,
            isActive: row.category.isActive,
          }

    return {
      episodeId: row.id,
      seriesId: row.series.id,
      seriesSlug: row.series.slug,
      seriesTitle: row.series.title,
      number: row.number,
      title: row.title,
      description: row.description,
      metaTitle: row.metaTitle,
      metaDescription: row.metaDescription,
      canonicalPath: row.canonicalPath,
      // URL 조립은 CDN 단일 진입점(`packages/storage/src/cdn.ts`)의 몫이다.
      // 이 계층은 키만 전달하고, 웹 계층이 `thumbUrl`/`cdnUrl` 로 바꾼다.
      thumbKey: row.thumbKey,
      ogImageKey: row.ogImageKey,
      durationSec: row.durationSec ?? row.asset?.durationSec ?? null,
      language: row.language,
      ageRating: row.ageRating,
      visibility: row.visibility,
      madeForKids: row.madeForKids,
      license: row.license,
      allowEmbed: row.allowEmbed,
      keywords: row.keywords,
      contentWarnings: row.contentWarnings,
      regionsAllowed: row.regionsAllowed,
      regionsBlocked: row.regionsBlocked,
      aiDisclosure: row.aiDisclosure,
      aiModels: row.aiModels,
      aiTools: row.aiTools,
      aiHumanRole: row.aiHumanRole,
      category,
      chapters,
      credits,
      subtitles,
      translations,
      creator: {
        handle: row.series.owner.handle,
        displayName: row.series.owner.displayName,
        avatarUrl: row.series.owner.avatarKey,
        tier: row.series.owner.tier,
        isVerified: row.series.owner.verifiedAt !== null,
      },
      publishedAt: row.publishedAt,
      viewCount: row.viewCount.toString(),
      likeCount: row.likeCount,
      commentCount: row.commentCount,
    }
  })
}

/**
 * sitemap 에 넣을 공개 에피소드.
 *
 * `UNLISTED` 는 링크를 아는 사람만 보는 상태다. sitemap 에 넣으면 그 전제가
 * 깨지므로 `PUBLIC` 만 담는다. 지역 차단이 걸린 작품도 일부 지역에서는
 * 유효하므로 포함한다 — 차단은 요청 시점에 판단할 일이다.
 */
export function listSitemapEpisodes(limit: number): Promise<SitemapEntry[]> {
  return executeDb(async () => {
    const rows = await db.episode.findMany({
      where: {
        status: 'PUBLISHED',
        visibility: 'PUBLIC',
        deletedAt: null,
        publishedAt: { not: null },
        series: { deletedAt: null, visibility: 'PUBLIC' },
      },
      select: { id: true, updatedAt: true, canonicalPath: true },
      orderBy: { publishedAt: 'desc' },
      take: limit,
    })
    return rows.map((row) => ({
      path: row.canonicalPath ?? `/watch/${row.id}`,
      lastModified: row.updatedAt,
    }))
  })
}

export function listSitemapSeries(limit: number): Promise<SitemapEntry[]> {
  return executeDb(async () => {
    const rows = await db.series.findMany({
      where: {
        deletedAt: null,
        visibility: 'PUBLIC',
        episodes: { some: { status: 'PUBLISHED', deletedAt: null } },
      },
      select: { id: true, updatedAt: true, canonicalPath: true },
      orderBy: { updatedAt: 'desc' },
      take: limit,
    })
    return rows.map((row) => ({
      path: row.canonicalPath ?? `/series/${row.id}`,
      lastModified: row.updatedAt,
    }))
  })
}

/** 공개 프로필만. `profileVisibility` 가 PUBLIC 이 아니면 색인 대상이 아니다. */
export function listSitemapCreators(limit: number): Promise<SitemapEntry[]> {
  return executeDb(async () => {
    const rows = await db.user.findMany({
      where: {
        deletedAt: null,
        status: 'ACTIVE',
        profileVisibility: 'PUBLIC',
        series: { some: { deletedAt: null, visibility: 'PUBLIC' } },
      },
      select: { handle: true, updatedAt: true },
      orderBy: { updatedAt: 'desc' },
      take: limit,
    })
    return rows.map((row) => ({
      path: `/u/${row.handle}`,
      lastModified: row.updatedAt,
    }))
  })
}

/** 태그 페이지. `useCount` 상위만 담는다 — 꼬리 태그는 색인 가치가 없다. */
export function listSitemapTags(limit: number): Promise<SitemapEntry[]> {
  return executeDb(async () => {
    const rows = await db.tag.findMany({
      where: { useCount: { gt: 0 } },
      select: { name: true },
      orderBy: { useCount: 'desc' },
      take: limit,
    })
    const now = new Date()
    return rows.map((row) => ({
      path: `/tags/${encodeURIComponent(row.name)}`,
      lastModified: now,
    }))
  })
}

export function listActiveCategories(): Promise<readonly Category[]> {
  return executeDb(async () => {
    const rows = await db.category.findMany({
      where: { isActive: true },
      orderBy: { order: 'asc' },
    })
    return rows.map((row) => ({
      id: row.id,
      slug: row.slug,
      nameKo: row.nameKo,
      nameEn: row.nameEn,
      order: row.order,
      isActive: row.isActive,
    }))
  })
}
