import type { Episode as PrismaEpisode } from '@prisma/client'
import type { Episode } from '@aidream/core'

export function mapEpisode(row: PrismaEpisode): Episode {
  return {
    id: row.id,
    seriesId: row.seriesId,
    seasonId: row.seasonId,
    assetId: row.assetId,
    number: row.number,
    title: row.title,
    description: row.description,
    thumbKey: row.thumbKey,
    status: row.status,
    ageRating: row.ageRating,
    visibility: row.visibility,
    durationSec: row.durationSec,
    language: row.language,
    categoryId: row.categoryId,
    keywords: row.keywords,
    allowEmbed: row.allowEmbed,
    allowDownload: row.allowDownload,
    recordedAt: row.recordedAt,
    metaTitle: row.metaTitle,
    metaDescription: row.metaDescription,
    ogImageKey: row.ogImageKey,
    canonicalPath: row.canonicalPath,
    madeForKids: row.madeForKids,
    license: row.license,
    contentWarnings: row.contentWarnings,
    regionsAllowed: row.regionsAllowed,
    regionsBlocked: row.regionsBlocked,
    aiDisclosure: row.aiDisclosure,
    aiModels: row.aiModels,
    aiTools: row.aiTools,
    aiHumanRole: row.aiHumanRole,
    aiGeneratedPct: row.aiGeneratedPct,
    publishAt: row.publishAt,
    publishedAt: row.publishedAt,
    viewCount: row.viewCount.toString(),
    likeCount: row.likeCount,
    commentCount: row.commentCount,
    shareCount: row.shareCount,
    impressionCount: row.impressionCount.toString(),
    avgWatchSec: row.avgWatchSec,
    rankScore: row.rankScore,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    deletedAt: row.deletedAt,
  }
}
