import type { User as PrismaUser } from '@prisma/client'
import type { User } from '@aidream/core'

export function mapUser(row: PrismaUser): User {
  return {
    id: row.id,
    handle: row.handle,
    email: row.email,
    emailVerified: row.emailVerified,
    passwordHash: row.passwordHash,
    displayName: row.displayName,
    bio: row.bio,
    avatarKey: row.avatarKey,
    role: row.role,
    status: row.status,
    tier: row.tier,
    tierPoints: row.tierPoints,
    tierEvaluatedAt: row.tierEvaluatedAt,
    roleGrantedAt: row.roleGrantedAt,
    roleGrantedBy: row.roleGrantedBy,
    bannerKey: row.bannerKey,
    channelDescription: row.channelDescription,
    channelKeywords: row.channelKeywords,
    trailerEpisodeId: row.trailerEpisodeId,
    profileVisibility: row.profileVisibility,
    hideFollowerCount: row.hideFollowerCount,
    verifiedAt: row.verifiedAt,
    country: row.country,
    locale: row.locale,
    timezone: row.timezone,
    birthDate: row.birthDate,
    gender: row.gender,
    signupPurpose: row.signupPurpose,
    phone: row.phone,
    phoneVerifiedAt: row.phoneVerifiedAt,
    defaultAgeRating: row.defaultAgeRating,
    defaultLanguage: row.defaultLanguage,
    defaultLicense: row.defaultLicense,
    followerCount: row.followerCount,
    followingCount: row.followingCount,
    seriesCount: row.seriesCount,
    episodeCount: row.episodeCount,
    totalViews: row.totalViews.toString(),
    lastLoginAt: row.lastLoginAt,
    lastSeenAt: row.lastSeenAt,
    loginCount: row.loginCount,
    signupIpHash: row.signupIpHash,
    signupUserAgent: row.signupUserAgent,
    signupReferrer: row.signupReferrer,
    utmSource: row.utmSource,
    utmMedium: row.utmMedium,
    utmCampaign: row.utmCampaign,
    suspendedUntil: row.suspendedUntil,
    suspendReason: row.suspendReason,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    deletedAt: row.deletedAt,
  }
}
